package org.springframework.social.security.model;
// Generated Oct 13, 2012 4:29:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Socialuser generated by hbm2java
 */
public class Socialuser  implements java.io.Serializable {


     private String userId;
     private String providerId;
     private String providerUserId;
     private int rank;
     private String displayName;
     private String profileUrl;
     private String imageUrl;
     private String accessToken;
     private String secret;
     private String refreshToken;
     private String expireTime;
     private Date createDate;

    public Socialuser() {
    }

	
    public Socialuser(String userId, String providerId, int rank, String accessToken) {
        this.userId = userId;
        this.providerId = providerId;
        this.rank = rank;
        this.accessToken = accessToken;
    }
    public Socialuser(String userId, String providerId, String providerUserId, int rank, String displayName, String profileUrl, String imageUrl, String accessToken, String secret, String refreshToken, String expireTime, Date createDate) {
       this.userId = userId;
       this.providerId = providerId;
       this.providerUserId = providerUserId;
       this.rank = rank;
       this.displayName = displayName;
       this.profileUrl = profileUrl;
       this.imageUrl = imageUrl;
       this.accessToken = accessToken;
       this.secret = secret;
       this.refreshToken = refreshToken;
       this.expireTime = expireTime;
       this.createDate = createDate;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getProviderId() {
        return this.providerId;
    }
    
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getProviderUserId() {
        return this.providerUserId;
    }
    
    public void setProviderUserId(String providerUserId) {
        this.providerUserId = providerUserId;
    }
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getProfileUrl() {
        return this.profileUrl;
    }
    
    public void setProfileUrl(String profileUrl) {
        this.profileUrl = profileUrl;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getAccessToken() {
        return this.accessToken;
    }
    
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }
    public String getSecret() {
        return this.secret;
    }
    
    public void setSecret(String secret) {
        this.secret = secret;
    }
    public String getRefreshToken() {
        return this.refreshToken;
    }
    
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }
    public String getExpireTime() {
        return this.expireTime;
    }
    
    public void setExpireTime(String expireTime) {
        this.expireTime = expireTime;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


